# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170206_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(choices=[(2, 'User'), (1, 'Admin')]),
        ),
    ]
