# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170207_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.User', verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(choices=[(2, 'User'), (1, 'Admin')]),
        ),
    ]
