# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170208_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.IntegerField(blank=True, choices=[(2, 'User'), (1, 'Admin')], null=True),
        ),
    ]
