# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170208_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'User')], null=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='type_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ExtendUser', verbose_name='Тип пользователя'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
