# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170208_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город'),
        ),
    ]
