# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170208_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='type_user',
            field=models.IntegerField(choices=[(2, 'User'), (1, 'Admin')], default=1, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(blank=True, choices=[(2, 'Я счастливый человек'), (3, 'Я несчастен'), (1, 'Я смелый человек')], verbose_name='1 Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_2',
            field=models.IntegerField(blank=True, choices=[(2, 'Я счастливый человек'), (3, 'Я несчастен'), (1, 'Я успешный человек')], verbose_name='2 Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_3',
            field=models.IntegerField(blank=True, choices=[(1, 'Я хорошо вижу'), (2, 'Я счастливый человек'), (3, 'Я не вижу')], verbose_name='3 Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.IntegerField(choices=[(3, 'Тест на зоркость'), (1, 'Тест на смелось'), (2, 'Тест на успешность')], default=1),
        ),
    ]
