# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20170208_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='question_title',
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='type_user',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'User')], default=1, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(blank=True, choices=[(3, 'Я несчастен'), (2, 'Я счастливый человек'), (1, 'Я смелый человек')], verbose_name='1 Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_3',
            field=models.IntegerField(blank=True, choices=[(3, 'Я не вижу'), (2, 'Я счастливый человек'), (1, 'Я хорошо вижу')], verbose_name='3 Вопрос'),
        ),
    ]
