# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20170208_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='type_user',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_1',
            field=models.IntegerField(blank=True, choices=[(2, 'Я счастливый человек'), (1, 'Я смелый человек'), (3, 'Я несчастен')], verbose_name='1 Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_2',
            field=models.IntegerField(blank=True, choices=[(2, 'Я счастливый человек'), (1, 'Я успешный человек'), (3, 'Я несчастен')], verbose_name='2 Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.IntegerField(choices=[(1, 'Тест на смелось'), (2, 'Тест на успешность'), (3, 'Тест на зоркость')], verbose_name='Название вопроса'),
        ),
        migrations.DeleteModel(
            name='ExtendUser',
        ),
    ]
