# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170214_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
