# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='type_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
